/*
Copyright (c) 2020, Dr. Hans-Walter Latz
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * The name of the author may not be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER "AS IS" AND ANY EXPRESS
OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

package dev.hawala.st80vm.memory;

/**
 * Utility methods for raising a RuntimeException for specific situations where
 * a Object Memory functionality cannot be executed, indicating that the Smalltalk
 * engine ran into a bug (assuming that the instruction sequences generated by the
 * Smalltalk compiler are correct), like attempting to access the heap for a small
 * integer object or accessing an objects heap outside the memory area allocated to
 * this object or simply an out-of-memory situation.
 * <p>
 * In all cases, the Smalltalk engine is stopped and the running program aborted.
 * </p>
 * 
 * @author Dr. Hans-Walter Latz / Berlin (2020)
 */
/* package-access */ class MisuseHandler {

	public static RuntimeException ofIntMethod(String method) {
		flush();
		return new RuntimeException("Misuse of SmallInteger objectTable entry, method " + method + "()");
	}
	
	public static RuntimeException ofObjectMethod(String method) {
		flush();
		return new RuntimeException("Misuse of Object objectTable entry, method " + method + "()");
	}
	
	public static RuntimeException ofObjectMemory(String method, int index, String info) {
		flush();
		String tail = (info != null) ? " - " + info : "";
		return new RuntimeException("Error accessing heap space of object at index " + index + " by method " + method + "()" + tail);
	}
	
	public static RuntimeException outOfMemory(String which) {
		flush();
		return new RuntimeException("Smalltalk-80-OutOfMemory(" + which + ")");
	}
	
	private static void flush() {
		System.out.flush();
		try { Thread.sleep(200); } catch (InterruptedException e) { }
	}
}
